# ---------------------------------------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TagnumElite
subtitle: Placeholder subtitle
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: TagnumElite
email: tagnumelite@elitekast.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tagnumelite.com" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://twitter.com/TagnumElite
facebook_url:
discord_url: https://discord.gg/P96kg3A
instagram_url:
linkedin_url:
github_url: https://github.com/TagnumElite
steam_url: https://steamcommunity.com/id/TagnumElite/
slack_url:
dribbble_url:
npm_url: https://www.npmjs.com/~tagnumelite
pypi_url: https://pypi.org/user/TagnumElite/
stack_exchange_url: https://stackexchange.com/users/4947564/tagnumelite
spotify_url: https://open.spotify.com/user/k9aryty1rpng9fexrxejs43fi?si=N27ahQlGSwejC0_7oWCmAA
strava_url:
twitch_url: https://www.twitch.tv/tagnumelite
tumblr_url:
xbox_url:
playstation_url: https://my.playstation.com/profile/TagnumElite
digital_ocean_url: https://m.do.co/c/da7c1e7ccc7a
youtube_url: https://www.youtube.com/channel/UChphbk4d1OvPilYwRnj_Z5w

# Google Analytics Tracking ID goes here:
google_analytics: UA-49499868-5

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
