# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TagnumElite
subtitle: Psuedo-Random Coder
email: me@tagnumelite.com
description: >- # this means to ignore newlines until "baseurl:"
  A website for me, TagnumElite, to showcase, discuss and explore
  my projects ands thoughts.
twitter_username: TagnumElite
github_username: TagnumElite
minimal_mistakes_skin: "dark"
logo: "/assets/images/80x80.png"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - old/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "TagnumElite"
  avatar : "/assets/images/avatar.jpg"
  bio    : "{{ Insert biography here - ERR: Life Not Found }}"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tagnumelite.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TagnumElite"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TagnumElite"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/XHCBxPA"
    - label: "PayPal"
      icon: "fab fa-fw fa-paypal"
      url: "https://paypal.me/TagnumElite"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/TagnumElite/"
    - label: "NPM"
      icon: "fab fa-fw fa-npm"
      url: "https://www.npmjs.com/~tagnumelite"
    - label: "PyPi"
      icon: "fab fa-fw fa-python"
      url: "https://pypi.org/user/TagnumElite/"
    - label: "Stack Exchange"
      icon: "fab fa-fw fa-stack-exchange"
      url: "https://stackexchange.com/users/4947564/tagnumelite"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/tagnumelite"
    - label: "PlayStation"
      icon: "fab fa-fw fa-playstation"
      url: "https://my.playstation.com/profile/TagnumElite"
    - label: "Digital Ocean"
      icon: "fab fa-fw fa-digital-ocean"
      url: "https://m.do.co/c/da7c1e7ccc7a"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UChphbk4d1OvPilYwRnj_Z5w"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TagnumElite"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TagnumElite"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/XHCBxPA"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/TagnumElite/"
    - label: "NPM"
      icon: "fab fa-fw fa-npm"
      url: "https://www.npmjs.com/~tagnumelite"
    - label: "PyPi"
      icon: "fab fa-fw fa-python"
      url: "https://pypi.org/user/TagnumElite/"
    - label: "Stack Exchange"
      icon: "fab fa-fw fa-stack-exchange"
      url: "https://stackexchange.com/users/4947564/tagnumelite"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/tagnumelite"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UChphbk4d1OvPilYwRnj_Z5w"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

social:
  name: TagnumElite
  links:
    - "https://twitter.com/TagnumElite"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-49499868-5"
    anonymize_ip: false # default

comments:
  provider: "giscus"
  giscus:
    repo_id              : "MDEwOlJlcG9zaXRvcnkyMTIwMjMyODY="
    category_name        : "Comments"
    category_id          : "DIC_kwDODKM39s4COhbM"
    discussion_term      : "pathname"
    reactions_enabled    : '1'
    theme                : "dark"
